config/routes.rb
Rails.application.routes.draw do

root "welcome#index"
get "about" => "welcome#about"
get "project" => "welcome#project"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
	end

	def about
	end

	def project
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tfc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
<%= link_to "Home", root_path%>
<%= link_to "About", about_path%>
<%= link_to "Final Project", project_path%>
</div>


<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About me!</h1>

<ul>
	<li>Name: Alessandro Cetera</li>
	<li>Email: alessandro.cetera@gmail.com</li>	
	<li>Birthday: Sept. 25 1990</li>
	<li>Hometown: Jersey City, NJ</li>
	<li>Favorite Food: Pizza</li>
	<li>Favorite Movie: The Matrix</li>
	<li>Favorite Band: Antonio Venditti</li>
</ul>

app/views/welcome/index.html.erb


<h1>Welcome!</h1>

app/views/welcome/project.html.erb
<h1>Final Project</h1>

<div>This is my idea for a project:</div>
	<ul>
		<li>Name: Tinder for Clothes </li>
		<li>Description: Simple site that allows users to up or down vote clothes taken from the Amazon API</li>
	</ul>
</div>